### Get all trips
GET http://localhost:3000/trips

### Get all trips 404
GET http://localhost:3000/trips4004

### Get single trip
GET http://localhost:3000/trips/1

### Create trip
POST http://localhost:3000/trips
Content-Type: application/json

{
    "name": "Trip to Jamaika",
    "date": "2024-03-30",
    "country": "Jamaika",
    "city": "JCity",
    "rating": 3,
    "description": "Trip good islands",
    "price": 1350,
    "user_id": 2,
    "image_main": "jamaika.jpeg"
}

### Get single trip
DELETE http://localhost:3000/trips/5